# Generated by Django 6.0.5 on 2026-05-29 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('flag_code', models.CharField(help_text='e.g., US, UK, CA', max_length=10)),
                ('match_status', models.CharField(choices=[('safe', 'Safe Match'), ('possible', 'Possible Match'), ('reach', 'Reach School')], default='possible', max_length=20)),
                ('cost_per_year', models.IntegerField()),
                ('ielts_requirement', models.FloatField()),
                ('sat_requirement', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ielts_score', models.FloatField(default=7.5)),
                ('sat_score', models.IntegerField(default=1320)),
                ('budget', models.IntegerField(default=15000, help_text='Annual budget in USD')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
