# Generated by Django 6.0.4 on 2026-05-29 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unichance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('sop', 'Statement of Purpose (SOP)'), ('lor', 'Letters of Recommendation (LOR)'), ('transcript', 'Academic Transcripts'), ('cv', 'Curriculum Vitae / Resume')], max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='unichance.userprofile')),
            ],
        ),
    ]
