# Generated by Django 6.0.4 on 2026-05-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unichance', '0002_applicationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
