# Generated by Django 6.0.5 on 2026-05-29 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unichance', '0003_university_application_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdocument',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='university',
            name='flag_code',
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='doc_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='university',
            name='match_status',
            field=models.CharField(default='possible', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ielts_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sat_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
