# Generated by Django 6.0.4 on 2026-05-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unichance', '0004_remove_applicationdocument_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='application_deadline',
        ),
        migrations.AddField(
            model_name='university',
            name='acceptance_rate',
            field=models.IntegerField(default=15, help_text='Percentage value'),
        ),
        migrations.AddField(
            model_name='university',
            name='avg_starting_salary',
            field=models.IntegerField(default=75000, help_text='USD per year'),
        ),
        migrations.AddField(
            model_name='university',
            name='city',
            field=models.CharField(default='Campus Base', max_length=100),
        ),
        migrations.AddField(
            model_name='university',
            name='deadline',
            field=models.CharField(default='January 15', max_length=100),
        ),
        migrations.AddField(
            model_name='university',
            name='living_costs',
            field=models.IntegerField(default=15000, help_text='Estimated yearly living expenses'),
        ),
        migrations.AddField(
            model_name='university',
            name='required_essays',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='university',
            name='scholarship_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='university',
            name='top_recruiters',
            field=models.CharField(default='Google, Microsoft, McKinsey', max_length=255),
        ),
        migrations.AlterField(
            model_name='university',
            name='ielts_requirement',
            field=models.FloatField(default=6.5),
        ),
        migrations.AlterField(
            model_name='university',
            name='match_status',
            field=models.CharField(default='Match', max_length=50),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='university',
            name='sat_requirement',
            field=models.IntegerField(default=1200),
        ),
    ]
