# Generated by Django 6.0.5 on 2026-05-30 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unichance', '0005_remove_university_application_deadline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='deadline',
            new_name='application_deadline',
        ),
    ]
